apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
data:
  DB_HOST:                                          # Postgresql host address
  DB_USER:                                          # Postgresql superuser name
  DB_PASSWORD:                                      # Postgresql superuser password
  BACKUP_DIR:                                       # Name of the directory for GCE bucket mount
  PATH_TO_KEY_FILE:                                 # Path to Google service account key
  BUCKET_NAME:                                      # Name of the GCS bucket storage
  DB_NAME:                                          # Name of the database for backup

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "* * * * *"                             # Set schedule on your needs
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: <image-name>                     # Image can be any with gcsfuse installed
            envFrom:
            - configMapRef:
                name: backup-config
            securityContext:
              privileged: true
              capabilities:
                add: ["SYS_ADMIN"]
            volumeMounts:
              - name: secret-volume
                mountPath: /var/secrets
          restartPolicy: Never
          volumes:
            - name: secret-volume
              secret:
                secretName: <name of tne secret>    # Kubernetes secret with Google service account key
