---
- name: create user for replication
  community.postgresql.postgresql_user:
    db: test_students
    name: test_user
    password: "{{ test_user_password }}" 
    role_attr_flags: REPLICATION,LOGIN
    login_user: postgres
    login_password: "{{ db_password }}"
    login_host: localhost

- name: add role privileges to database test_users
  community.postgresql.postgresql_privs:
    database: test_students
    state: present
    privs: ALL
    type: database
    roles: test_user
    login_user: postgres
    login_password: "{{ db_password }}"
    login_host: localhost

- name: add priveleges on schema public to test_user
  community.postgresql.postgresql_privs:
    db: test_students
    privs: ALL
    #type: schema
    objs: ALL_IN_SCHEMA
    role: test_user
    login_user: postgres
    login_password: "{{ db_password }}"
    login_host: localhost

- name: create publication for 
  community.postgresql.postgresql_publication:
    db: test_students
    name: test_publication
    login_user: postgres
    login_password: "{{ db_password }}"
    login_host: localhost
     
