---
- name: copy data files to master server
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_items:
    - result.csv
    - students.csv
    - test_import.sql

- name: load data to database test_students
  shell: PGPASSWORD={{ db_password }} psql -h localhost -U postgres -d test_students -f /tmp/test_import.sql
