version: "3.3"
services:
  web:
    image: "yurickch/test_web"
    env_file: .env.web
    ports:
     - "8081-8085:80"

  java:
    build:
     context: .
     dockerfile: Dockerfile
    env_file: .env.java
    ports:
      - "8888:8080"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db", "/usr/local/tomcat/bin/catalina.sh", "run"]

  db:
    image: "postgres"
    env_file: .env.db
    ports:
      - "5432:5432"
