---
- name: Update repo and install dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Install Docker repo key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install Docker packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-docker  
    state: present

- name: Add user to docker group 
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Reset connection for applying changes
  meta: reset_connection

- name: Check installation
  shell: docker run --rm hello-world
  register: check_hello

- name: run Docker test image hello-world
  debug:
    msg:
      - "{{ check_hello.stdout_lines }}"

- name: Remove unnessary images
  shell: docker rmi hello-world  

