apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  labels:
    app: webapp
data:
  DJANGO_SECRET_KEY     : {{ .Values.envs.django_secret_key }}
  DJANGO_DEBUG          : {{ .Values.envs.django_debug | quote }}
  DJANGO_ALLOWED_HOSTS  : {{ .Values.envs.django_allowed_hosts | quote }}
  DATABASE_NAME         : {{ .Values.envs.django_db_name }}
  DATABASE_USERNAME     : {{ .Values.envs.django_db_username }}
  DATABASE_PASSWORD     : {{ .Values.envs.django_user_password }}
  DATABASE_HOST         : postgres                      
  DATBASE_PORT          : {{ .Values.envs.database_port | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: webapp
      protocol: TCP
      port: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.container.image_webapp }}
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: webapp-config
      imagePullSecrets:
      - name: bravo-registry
