apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
data:
  DB_HOST: postgres
  DB_USER: {{ .Values.envs.postgres_user }}
  DB_PASSWORD: {{ .Values.envs.postgres_password }}
  BACKUP_DIR: "/root/backup"
  PATH_TO_KEY_FILE: "/var/secrets/key.json"
  BUCKET_NAME: bravo-test-bucket
  DB_NAME: {{ .Values.envs.django_db_name }}

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: yurickch/docker-gcs:latest
            envFrom:
            - configMapRef:
                name: backup-config
            securityContext:
              privileged: true
              capabilities:
                add: ["SYS_ADMIN"]
            volumeMounts:
              - name: secret-volume
                mountPath: /var/secrets
          restartPolicy: Never
          volumes:
            - name: secret-volume
              secret:
                secretName: gcs-bravo-bucket
