---
- name: create subscription to master server
  community.postgresql.postgresql_subscription:
    db: test_students
    name: test_subscription
    state: present
    publications: test_publication
    connparams:
      host: 172.31.14.40
      port: 5432
      user: test_user
      password: "{{ test_user_password }}"
      dbname: test_students
    login_user: postgres
    login_password: "{{ db_password }}"
    login_host: localhost
