# This is a test workflow to create docker image

name: test-docker

 
on:
  push:
    branches: [ master ]
  
jobs:

  build:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v2

      - name: goto in build directory
        run: |
         cd task3/subtask3/
         ls -la
         docker build . -t yurickch/test_web:latest
      - uses: docker/build-push-action@v1
        with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}
         repository: yurickch/test_web
         tags: latest
      
