# This is a test workflow to create docker image

name: test-docker

 
on:
  push:
    branches: [ master ]
  
jobs:

  build:
    runs-on: ubuntu-latest

    
    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}
      
      - name: Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: build - push
        uses: docker/build-push-action@v2
        with:
         context: .
         file: ./task3/subtask3/Dockerfile
         push: true
         tags: latest
      
